# Anchors
when_pr_push: &when_pr_push
  when:
    event:
      - push
      - pull_request

docker-compose: &docker-compose
  <<: *when_pr_push
  image: docker/compose:1.22.0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

test: &test
  <<: *when_pr_push
  image: fidals/stb:dev
  environment:
    - TEST_ENV=true
    - DJANGO_SETTINGS_MODULE=stroyprombeton.settings.dev
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=test
    - POSTGRES_URL=postgres
    - POSTGRES_DB=test
    - RABBITMQ_DEFAULT_USER=rabbitmq
    - RABBITMQ_DEFAULT_PASS=test
    - RABBITMQ_URL=rabbitmq
    - RABBITMQ_PORT=5672
    - SELENIUM_URL=http://selenium:4444/wd/hub
    # Hardcoded env values because of drone secret's bug. See stb#263
    - SELENIUM_TIMEOUT_SECONDS=300
    - SELENIUM_WAIT_SECONDS=300

lint: &lint
  <<: *when_pr_push
  group: lint

service: &service
  <<: *when_pr_push
  group: service

# CI config
branches: master

workspace:
  base: /drone
  path: stroyprombeton/

pipeline:
  nodejs-build:  # with `npm install` inside
    <<: *docker-compose
    commands:
      - cd docker/
      # nodejs build is not in `docker-build` section,
      # because we have this deps:
      # build nodejs -> gulp build -> build python-prod
      - docker-compose -f docker-compose-build.yml build nodejs

  gulp-build:
    <<: *when_pr_push
    image: fidals/stb-nodejs:dev
    commands:
      - cp -r /usr/app/src/node_modules .
      - gulp build

  python-build:
    <<: *docker-compose
    commands:
      - cd docker/
      # Build python images with sources and static files
      - docker-compose -f docker-compose-build.yml build python-dev python-prod

  fast-test:
    <<: *test
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py test --parallel --tag fast -k

  slow-test:
    <<: *test
    commands:
      - python manage.py test --parallel --tag slow -k

  lint-coala:
    <<: *lint
    image: fidals/coala-ci
    commands:
      - coala --ci -j 2

  lint-pdd:
    <<: *lint
    image: fidals/pdd-ci
    commands:
      - pdd --verbose
        --exclude=node_modules/**/* --exclude=static/**/*
        --exclude=media/**/*
        --exclude=.idea/**/*
        --exclude=front_build
        --exclude=front/images
        --exclude=**/*.pyc
        --exclude=**/*.jpg
        -f report.xml

  docker-push:
    image: docker:latest
    environment:
      - DOCKER_HUB_LOGIN=${DOCKER_HUB_LOGIN}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
    commands:
      - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
      - docker push fidals/stb-nodejs:dev
      - docker push fidals/stb:dev
      - docker push fidals/stb:prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ DOCKER_HUB_LOGIN, DOCKER_HUB_PASSWORD ]
    when:
      event: push

  docker-up:
    <<: *docker-compose
    commands:
      - cd docker/
      - cp drone_env/* env_files/
      - cp drone_env/.env .
      - docker-compose up -d app
      - docker-compose stop

  docker-rm:
    <<: *docker-compose
    commands:
      - cd docker/
      - cp drone_env/* env_files/
      - cp drone_env/.env .
      - docker-compose rm -fs

services:
  postgres:
    <<: *service
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

  rabbitmq:
    <<: *service
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=test

  selenium:
    <<: *service
    image: selenium/standalone-chrome-debug:3.10.0
    environment: # https://github.com/SeleniumHQ/docker-selenium/issues/392
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    shm_size: 4G
    volumes: # https://github.com/SeleniumHQ/docker-selenium#running-the-images
      - /dev/shm:/dev/shm
