version: "2"

services:
  stb_prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: fidals/stb
    container_name: stb_prod
    restart: always
    environment:
      - ALLOWED_HOSTS=*
      - SECRET_KEY=$SECRET_KEY
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - DJANGO_SETTINGS_MODULE=stroyprombeton.settings.prod
      - DATABASE_URL=postgres://postgres:$DB_PASS@stb_db_prod/stb_prod
      - BROCKER_URL=amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@stb_rabbitmq:5672/
    entrypoint:
      - circusd
      - /etc/circus/stb_prod.ini
    volumes:  # TODO - divide volumes on dev/ and prod/
      - /opt/media/stroyprombeton:/opt/stroyprombeton/app/media
    ports:
      - "8020:80"
    links:
      - stb_rabbitmq

  stb_dev:
    image: fidals/stb
    container_name: stb_dev
    environment:
      - ALLOWED_HOSTS=*
      - SECRET_KEY=$SECRET_KEY
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - DJANGO_SETTINGS_MODULE=stroyprombeton.settings.dev
      - DATABASE_URL=postgres://postgres:$DB_PASS@stb_db_dev/stb_dev
    entrypoint:
      - circusd
      - /etc/circus/stb_dev.ini
    ports:
      - "8021:80"
    links:  # can't be inherited
      - stb_db_dev
    volumes:  # TODO - divide volumes on dev/ and prod/
      - /opt/media/stroyprombeton:/opt/stroyprombeton/app/media

  stb_db_prod:
    image: postgres:9.5
    container_name: stb_db_prod
    restart: always
    environment:
      POSTGRES_DB: "stb_prod"
      POSTGRES_PASSWORD: "$DB_PASS"
    volumes:
      - /var/lib/postgresql/data

  stb_db_dev:
    image: postgres:9.5
    container_name: stb_db_dev
    environment:
      POSTGRES_DB: "stb_dev"
      POSTGRES_PASSWORD: "$DB_PASS"
    volumes:
      - /var/lib/postgresql/data

  stb_rabbitmq:
    image: rabbitmq:management-alpine
    container_name: stb_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - "5674:5672"
      - "15674:15672"
