version: '2'

services:

  app:
    image: fidals/stb:dev
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
      - env_files/ports
    environment:
      - ALLOWED_HOSTS=*
      - TEST_ENV=true
      - PYTHONUNBUFFERED=0
    ports:
      - $VIRTUAL_HOST_EXPOSE_PORT:$VIRTUAL_HOST_PORT
      - $VIRTUAL_HOST_LIVESERVER_PORT
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - stb-backend
      - stb-frontend
    volumes_from:
      - nodejs
    volumes:
      - ./../:$SRC_DIR
      # contains refarm-site modules
      - $DEPS_DIR
      # Thus, you can work with apps related to the refarm-site
      # - $REFARM_SRC/stbarch:/root/.local/lib/python3.6/site-packages/stbarch
    # @todo #150 Validate if `.env` is full
    #  Is full means '.env` contains all keynames from `.env.dist`
    command: python manage.py runserver 0.0.0.0:$VIRTUAL_HOST_PORT

  nodejs:
    image: fidals/stb-nodejs:dev
    volumes:
      - $FRONT_BUILD_DIR
      # for SE's front development
      - ../gulpfile.babel.js:/usr/app/src_front/gulpfile.babel.js
      - ../package.json:/usr/app/src_front/package.json
      - ../front:/usr/app/src_front/front
    env_file:
      - env_files/paths

  postgres:
    image: postgres:9.5
    restart: always
    env_file:
      - env_files/credentials
    networks:
      - stb-backend
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    env_file:
      - env_files/credentials
    networks:
      - stb-backend
    # @todo #142:30m Check why rabbitmq exposes it's ports to host machine.
    #  And write doc or request some fix.
    ports:
      - 5674:5672
      - 15674:15672

  selenium:
    image: selenium/standalone-chrome-debug:3.10.0
    restart: always
    ports:
      - 4444
      # VNC port. Password: secret
      - 5900:5900
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    networks:
      - stb-backend
    # https://github.com/SeleniumHQ/docker-selenium#running-the-images
    shm_size: 4G
    volumes:
      - /dev/shm:/dev/shm

  lint:
    image: fidals/coala-ci
    working_dir: $SRC_DIR
    command: coala
    volumes_from:
      - app

  pdd:
    image: fidals/pdd-ci
    env_file:
      - env_files/paths
    working_dir: $SRC_DIR
    volumes_from:
      - app
    command: pdd --verbose --exclude=node_modules/**/* --exclude=static/**/* --exclude=media/**/* --exclude=doc/build/**/* -f report.xml

networks:
  stb-backend:
  stb-frontend:
