version: '2'

services:

  app:
    image: fidals/stb:dev
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
      - env_files/ports
    environment:
      - ALLOWED_HOSTS=*
      - TEST_ENV=true
      - PYTHONUNBUFFERED=0
    ports:
      - $VIRTUAL_HOST_DEV_PORT:8000
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - stb-backend
      - stb-frontend
    volumes:
      - ./../:$SRC_DIR
      # Thus, you can work with apps related to the refarm-site
      #- $REFARM_DIR/catalog:/root/.local/lib/python3.6/site-packages/catalog
      #- $REFARM_DIR/ecommerce:/root/.local/lib/python3.6/site-packages/ecommerce
      #- $REFARM_DIR/images:/root/.local/lib/python3.6/site-packages/images
      #- $REFARM_DIR/pages:/root/.local/lib/python3.6/site-packages/pages
      #- $REFARM_DIR/search:/root/.local/lib/python3.6/site-packages/search
      #- $REFARM_DIR/refarm_test_utils:/root/.local/lib/python3.6/site-packages/refarm_test_utils
      #- $REFARM_DIR/generic_admin:/root/.local/lib/python3.6/site-packages/generic_admin
    #  Is full means '.env` contains all keynames from `.env.dist`
    command: python manage.py runserver 0.0.0.0:8000

  nodejs:
    image: fidals/stb-nodejs:dev
    volumes:
      # Uncomment next line if you dev refarm-site's front
      # - ../../refarm-site/:$DEPS_DIR/
      # - ../gulpfile.babel.js:/usr/app/src/gulpfile.babel.js
      - ../front:/usr/app/src/front
      - ../front_build:/usr/app/src/front_build

  postgres:
    image: postgres:9.5
    restart: always
    env_file:
      - env_files/credentials
    networks:
      - stb-backend
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    env_file:
      - env_files/credentials
    networks:
      - stb-backend
    ports:
      - 5672
      - 15672

  selenium:
    image: selenium/standalone-chrome-debug:3.14.0
    restart: always
    ports:
      - 4444
      # VNC port. Password: secret
      - 5900:5900
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    networks:
      - stb-backend
    # https://github.com/SeleniumHQ/docker-selenium#running-the-images
    shm_size: 4G
    volumes:
      - /dev/shm:/dev/shm

  lint:
    image: fidals/coala-ci
    working_dir: $SRC_DIR
    command: coala
    volumes:
      - ./../:$SRC_DIR

  pdd:
    image: fidals/pdd-ci
    env_file:
      - env_files/paths
    working_dir: $SRC_DIR
    volumes:
      - ./../:$SRC_DIR
    command: pdd
    entrypoint:
      - pdd
      - --exclude=venv/**/*
      - --exclude=node_modules/**/*
      - --exclude=static/**/*
      - --exclude=media/**/*
      - --exclude=doc/build/**/*
      - --exclude=.idea/**/*
      - --exclude=front_build
      - --exclude=front/images
      - --exclude=**/*.pyc
      - --exclude=**/*.jpg
      - -f report.xml

networks:
  stb-backend:
  stb-frontend:
