version: '2'

services:

  app:
    image: fidals/stb:prod
    container_name: stb-python
    restart: always
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
      - env_files/ports
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - 8000
    volumes:
      - ../stroyprombeton/settings/local.py:$SRC_DIR/stroyprombeton/settings/local.py
      # contains refarm-site modules
      - $DEPS_DIR
      # source code volume
      - $SRC_DIR
      # contains media files
      - /opt/media/stroyprombeton/:$SRC_DIR/media/
    networks:
      - stb-backend
      - stb-frontend
    command: gunicorn stroyprombeton.wsgi:application -c /etc/gunicorn.py -b 0.0.0.0:8000

  # @todo #232:60m Create separated DB for stage.
  #  Stage should have it's own data independent of production.
  #  We'll test content change scripts with PO there.
  app-stage:
    image: fidals/stb:prod
    container_name: stb-python-stage
    restart: always
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
      - env_files/ports
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - $VIRTUAL_HOST_STAGE_PORT:8001
    volumes:
      # contains refarm-site modules
      - $DEPS_DIR
    networks:
      - stb-backend
      - stb-frontend
    command: gunicorn stroyprombeton.wsgi:application -c /etc/gunicorn.py -b 0.0.0.0:8001

  celery-beat:
    image: fidals/stb:prod
    container_name: stb-celery-beat
    restart: always
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
    depends_on:
      - app
    volumes:
      - ../stroyprombeton/settings/local.py:$SRC_DIR/stroyprombeton/settings/local.py
    networks:
      - stb-backend
    command: celery -A stroyprombeton beat -l info

  celery-default-worker:
    image: fidals/stb:prod
    container_name: stb-celery-default-worker
    restart: always
    env_file:
      - env_files/app
      - env_files/credentials
      - env_files/paths
    depends_on:
      - app
    volumes:
      - ../stroyprombeton/settings/local.py:$SRC_DIR/stroyprombeton/settings/local.py
    networks:
      - stb-backend
    command: celery -A stroyprombeton worker -E -n worker.default@%%h -l info -Q default

  nginx:
    image: fidals/stb-nginx:prod
    container_name: stb-nginx
    restart: always
    env_file:
      - env_files/ports
    volumes_from:
      - app
    ports:
        - $VIRTUAL_HOST_PORT:80
    networks:
      - stb-frontend
    command: nginx -g 'daemon off;'

  postgres:
    image: postgres:9.5
    restart: always
    container_name: stb-postgres
    env_file:
      - env_files/credentials
      - env_files/app
    networks:
      - stb-backend
    volumes:
      - /opt/database/stroyprombeton:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: stb-rabbitmq
    restart: always
    env_file:
      - env_files/app
      - env_files/credentials
    networks:
      - stb-backend
    ports:
      - 5672
      - 15672

  redis:
    image: redis:alpine
    container_name: stb-redis
    restart: always
    env_file:
      - env_files/credentials
    command: redis-server /data/redis.conf --requirepass $REDIS_PASSWORD
    volumes:
      - ../etc/redis/redis.conf:/data/redis.conf
    networks:
      - stb-backend
    ports:
      - 6379

  # Контейнер делает бэкапы по крону.
  # Бэкап - это несколько архивов: database.tar.gz, media.tar.gz, static.tar.gz
  # в директории /opt/backup/stroyprombeton
  backup-data:
    build:
      context: ..
      dockerfile: docker/images/cron/Dockerfile
    container_name: stb-backup-data
    volumes_from:
      - app
    volumes:
      - ../etc/backup/backup-entrypoint.sh:/usr/bin/entrypoint.sh
      - ../etc/backup/crontab:/etc/cron.d/crontab
      - /opt/backup/stroyprombeton:/opt/backup
      - /opt/database/stroyprombeton:/usr/app/src/database

networks:
  stb-backend:
  stb-frontend:
